version: '3.1'

services:
    app:
        build:
            context: .
            dockerfile: ./Containerfile
        volumes:
            - type: bind
              source: ./src
              target: /app/src
        ports:
            - '3000:3000'
